name: Websocket Server Deployment
on:
  push:
    branches: [main]
  
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        # with:
        # fetch-depth: 0

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.ws
          push: true
          tags: rickydocker3445/devops-turbo-websocket:${{github.sha}}

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo su
            docker pull rickydocker3445/devops-turbo-websocket:${{ github.sha }}

            docker stop websocket || true
            docker rm websocket || true

            docker run -d \
              --name websocket \
              -p 8080:8080 \
              -e DATABASE_URL='${{ secrets.DATABASE_URL }}' \
              rickydocker3445/devops-turbo-websocket:${{ github.sha }}
